--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.63.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20/05/2018 18:57:28
-- Server version: 5.7.17-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO lavajato.cliente(codigo, tela, pessoa_pessoa_id) VALUES
(1, 'Incluir', 1);
INSERT INTO lavajato.cliente(codigo, tela, pessoa_pessoa_id) VALUES
(2, 'Incluir', 2);
INSERT INTO lavajato.cliente(codigo, tela, pessoa_pessoa_id) VALUES
(3, 'Incluir', 6);
INSERT INTO lavajato.cliente(codigo, tela, pessoa_pessoa_id) VALUES
(4, 'Incluir', 7);
INSERT INTO lavajato.cliente(codigo, tela, pessoa_pessoa_id) VALUES
(5, 'Incluir', 8);
INSERT INTO lavajato.cliente(codigo, tela, pessoa_pessoa_id) VALUES
(6, 'Incluir', 9);