--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.63.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20/05/2018 18:57:30
-- Server version: 5.7.17-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(1, '960.911.991-37', '2007-05-01', '1984-08-18', 'Segundo Grau', 'Casado(a)', 'Pedro Henrique Vicente Osvaldo das Neves', 'Eduarda Lívia ', 'Danilo Leandro Lorenzo das Neves', 'SSP', '35759507', 'Masculino', 'Goiás');
INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(2, '581.461.321-11', '2000-01-06', '1993-11-17', 'Segundo Grau', 'Casado(a)', 'Joana Sandra Castro', 'Nicole Sebastiana ', 'Anthony Erick Marcos Vinicius Castro', 'SSP', '46757965', 'Feminino', 'Goiás');
INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(3, '977.143.461-67', '2006-02-05', '1993-03-03', 'Segundo Grau', 'Solteiro(a)', 'Ricardo Oliver Ribeiro', 'Eloá Bianca Isabela ', 'Julio Pietro Oliver Ribeiro', 'SSP', '401412659', 'Masculino', 'Goiás');
INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(4, '704.767.601-51', '2009-06-19', '2000-06-19', 'Segundo Grau', 'Solteiro(a)', 'Geraldo Isaac Tomás da Mata', 'Lara Sebastiana Manuela ', 'Rafael Danilo da Mata', 'SSP', '270421679', 'Masculino', 'Goiás');
INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(5, '390.206.131-62', '2000-06-05', '1982-12-09', 'Graduação', 'Casado(a)', 'Bento Ryan Monteiro', 'Hadassa Isadora Fabiana ', 'Filipe Luan Monteiro', 'SSP', '403162506', 'Masculino', 'Goiás');
INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(6, '898.078.661-11', NULL, '1989-10-02', 'Segundo Grau', 'Casado(a)', 'Jorge Giovanni Figueiredo', 'Louise Elisa', 'Matheus Heitor Caleb Figueiredo', 'SSP', '34462676', 'Masculino', 'Goiás');
INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(7, '074.172.691-25', NULL, '1989-03-04', 'Segundo Grau', 'Casado(a)', 'Isabelle Lorena Fernandes', 'Sabrina Clara Lavínia', 'Diogo Juan Lucas Fernandes', 'SSP', '34462676', 'Masculino', 'Goiás');
INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(8, '841.420.531-32', NULL, '1989-11-09', 'Segundo Grau', 'Casado(a)', 'Giovanna Helena Barros', 'Sabrina Clara Lavínia', 'Diogo Juan Lucas Fernandes', 'SSP', '34462676', 'Masculino', 'Goiás');
INSERT INTO lavajato.pessoa_fisica(pessoa_fisica_id, cpf, dt_exp_rg, dt_nascimento, escolaridade, estado_civil, nome, nome_pai, nome_mae, orgao_rg, rg, sexo, uf_exp_rg) VALUES
(9, '363.943.611-35', NULL, '1993-01-15', 'Segundo Grau', 'Casado(a)', 'Tânia Bianca Elisa Araújo', 'Fernanda Luciana', 'Joaquim Cláudio Araújo', 'SSP', '34462676', 'Masculino', 'Goiás');