--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.63.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20/05/2018 18:57:33
-- Server version: 5.7.17-log
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO lavajato.veiculo(codigo, tela, cor, marca, modelo, placa, tipo_veiculo) VALUES
(1, 'Incluir', 'Preto', 'Chevrolet', 'Celta', 'OGH-1195', 'Automóvel');
INSERT INTO lavajato.veiculo(codigo, tela, cor, marca, modelo, placa, tipo_veiculo) VALUES
(2, 'Incluir', 'Prata', 'Ford', 'Ka', 'NHT-5633', 'Automóvel');
INSERT INTO lavajato.veiculo(codigo, tela, cor, marca, modelo, placa, tipo_veiculo) VALUES
(3, 'Incluir', 'Amarelo', 'VolksWagem', 'AMAROK Trendline CD ', 'KDD-8402', 'Automóvel');
INSERT INTO lavajato.veiculo(codigo, tela, cor, marca, modelo, placa, tipo_veiculo) VALUES
(4, 'Incluir', 'Prata', 'Fiat', 'Doblo Cargo 1.8 mpi ', 'KEF-1048', 'Automóvel');
INSERT INTO lavajato.veiculo(codigo, tela, cor, marca, modelo, placa, tipo_veiculo) VALUES
(5, 'Incluir', 'Vermelho', 'Fiat', 'Palio Celebration 1.', 'KBL-7428', 'Automóvel');