--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.63.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20/05/2018 18:57:32
-- Server version: 5.7.17-log
-- Client version: 4.1
--


SET NAMES 'utf8';
