

INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(1, True, '2018-05-06', NULL, NULL, 'pedrohenriquevicenteosvaldodasneves_@abbott.com', NULL, NULL, 'Cliente', 'SIM', NULL, 'Pessoa Física', 'NAO', 1, 1, NULL, 1);
INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(2, True, '2018-05-06', NULL, NULL, 'joanasandracastro@sercoti.com.br', NULL, NULL, 'Cliente', 'SIM', NULL, 'Pessoa Física', 'NAO', 2, 2, NULL, 2);
INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(3, True, '2018-05-06', NULL, NULL, 'ricardooliverribeiro-90@focusgrafica.com.br', 'ricardo.ribeiro', NULL, 'Lavador', 'SIM', '123456', 'Pessoa Física', 'SIM', 3, 3, NULL, 3);
INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(4, True, '2018-05-06', NULL, NULL, 'geraldoisaactomasdamata-97@rubens.adm.br', NULL, NULL, 'Lavador', 'SIM', NULL, 'Pessoa Física', 'NAO', 4, 4, NULL, 4);
INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(5, True, '2018-05-06', NULL, NULL, 'bbentoryanmonteiro@i9pneus.com.br', NULL, NULL, 'Lavador', 'SIM', NULL, 'Pessoa Física', 'NAO', 5, 5, NULL, 5);
INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(6, True, '2018-05-20', NULL, NULL, 'jorgegiovannifigueiredo@lexos.com.br', NULL, NULL, 'Cliente', 'SIM', NULL, 'Pessoa Física', 'NAO', 6, 6, NULL, 6);
INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(7, True, '2018-05-20', NULL, NULL, 'isabellelorenafernandes-84@bitco.cc', NULL, NULL, 'Cliente', 'SIM', NULL, 'Pessoa Física', 'NAO', 7, 7, NULL, 7);
INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(8, True, '2018-05-20', NULL, NULL, 'giovannahelenabarros@dcabr.org.br', NULL, NULL, 'Cliente', 'SIM', NULL, 'Pessoa Física', 'NAO', 8, 8, NULL, 8);
INSERT INTO lavajato.pessoa(pessoa_id, ativo, dt_cadastro, dt_senha, dt_ult_acesso, email, login, observacao, perfil, perm_envio_mail, senha, tipo_pessoa, usuario_sistema, endereco_endereco_id, pessoaFisica_pessoa_fisica_id, pessoaJuridica_codigo, telefone_telefone_id) VALUES
(9, True, '2018-05-20', NULL, NULL, 'taniabiancaelisaaraujo@ericsson.com', NULL, NULL, 'Cliente', 'SIM', NULL, 'Pessoa Física', 'NAO', 9, 9, NULL, 9);